openapi: 3.0.0
info:
  title: An Extensive API
  version: 1.0.0
  description: API documentation for managing user information and handling requests.
servers:
  - url: http://localhost:8080/api

paths:
  /auth/login:
    post:
      summary: Gives user access to resources
      requestBody:  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              example-1:
                value:
                  email: "prebstamar"
                  password: "succesfulpasscode"
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                example-1:
                  value:
                    token: "djfikdoklsosjfodkdfi8489rjdksdodjdoldjdfl"
                    status: "successful"
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "invalid email or password"
                    status: "error"
                    code: 401
  /auth/magic-link:
    post:
      summary: Authentication with magic link
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MagicLinkRequest'
            examples:
              example-1:
                value:
                  email: "peter@gmail.com"
      responses:
        '200':
          description: Magic Link sent
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "invalid email or password"
                    status: "error"
                    code: 401
  /auth/change-password:
    post:
      summary: Changes the password of the user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
            examples:
              example-1:
                value:
                  oldPassword: "oldCode"
                  newPassword: "newCode"
      responses: 
        '200':
          description: Password changed
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "password incorrect"
                    status: "error"
                    code: 400
  /messages/email:
    post:
      summary: Users are able to send emails with this
      requestBody:  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
            examples:
              example-1:
                value:
                  emailTo: "prosper@gmail.com"
                  subject: "Welcome brother prosper"
                  body: "We want to welcome you into our denomination"
      responses: 
        '200':
          description: Email sent successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "error processing email request"
                    status: "error"
                    code: 400       
  /payments/stripe:
    post:
      summary: Processes stripe payment
      requestBody:  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripePaymentRequest'
            examples:
              example-1:
                value:
                  amount: 50.0
                  currency: "USD"
                  source: "tok_visa"
      responses: 
        '200':
          description: Payment successfully processed
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "error processing payment request"
                    status: "error"
                    code: 400
  /payments/flutterwave:
    post:
      summary: Processes flutterwave payment
      requestBody:  
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlutterwavePaymentRequest'
            examples:
              example-1:
                value:
                  amount: 150.0
                  currency: "NGN"
                  source: "flw_card"
      responses: 
        '200':
          description: Payment successfully processed
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "error processing payment request"
                    status: "error"
                    code: 400
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Returns a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value: [
                    {
                      "id": 1,
                      "name": "Prebor Tamarakro",
                      "email": "prebstamar@gmail.com",
                      "organization": {
                        "id": 1,
                        "name": "prebsOrg"
                      }
                    },
                    {
                      "id": 2,
                      "name": "Peter Emmanuel",
                      "email": "peteremma@gmail.com",
                      "organization": {
                        "id": 1,
                        "name": "prebsOrg"
                      }
                    }
                  ]
    post: 
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              example-1:
                value:
                  name: "Prebor Divine"
                  email: "divine@yahoo.com"
                  password_hash: "hashedPasscode"
                  organization_id: 1
      responses:
        '201':
          description: User has been added to database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 1
                    name: "Prebor Emmanuel"
                    email: "emma@gmail.com"
                    organization: {
                      id: 1,
                      name: "prebsOrg"
                    }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "User could not be persisted"
                    status: "error"
                    code: 400
  /users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: integer
      responses:
        '200':
          description: User has been found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 1
                    name: "Prebor Emmanuel"
                    email: "emma@gmail.com"
                    organization: {
                      id: 1,
                      name: "prebsOrg"
                    }
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "User could not be located"
                    status: "not found"
                    code: 404
    put:
      summary: Update user information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The Id of the user to update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
            examples:
              example-1:
                value:
                  email: "emma@gmail.com"
                  name:  "updated user"
                  password: "dgfhkodos"  
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 1
                    email: "emma@gmail.com"
                    name: "Prebor Emmanuel"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "User could not be located"
                    status: "not found"
                    code: 404
    delete:
      summary: Delete a user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "User could not be located"
                    status: "not found"
                    code: 404

  /blogs:
    post:
      summary: Create a new blog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
            examples:
              example-1:
                value:
                  title: "New Blog Title"
                  content: "This is the content of the new blog."
                  user_id: 1
      responses:
        '201':
          description: Blog has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
              examples:
                example-1:
                  value:
                    id: 1
                    title: "New Blog Title"
                    content: "This is the content of the new blog."
                    user: {
                      id: 1,
                      name: "Prebor Emmanuel"
                    }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "Blog could not be created"
                    status: "error"
                    code: 400
    get:
      summary: Get all blogs
      responses:
        '200':
          description: Returns a list of blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
              examples:
                example-1:
                  value: [
                    {
                      "id": 1,
                      "title": "First Blog",
                      "content": "This is the content of the first blog.",
                      "user": {
                        "id": 1,
                        "name": "Prebor Emmanuel"
                      }
                    },
                    {
                      "id": 2,
                      "title": "Second Blog",
                      "content": "This is the content of the second blog.",
                      "user": {
                        "id": 2,
                        "name": "Peter Emmanuel"
                      }
                    }
                  ]
  /blogs/{id}:
    get:
      summary: Get a blog by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Blog has been found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
              examples:
                example-1:
                  value:
                    id: 1
                    title: "First Blog"
                    content: "This is the content of the first blog."
                    user: {
                      id: 1,
                      name: "Prebor Emmanuel"
                    }
        '404':
          description: Blog not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "Blog could not be located"
                    status: "not found"
                    code: 404
    put:
      summary: Update a blog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Blog'
            examples:
              example-1:
                value:
                  title: "Updated Blog Title"
                  content: "This is the updated content of the blog."
      responses:
        '200':
          description: Blog updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
              examples:
                example-1:
                  value:
                    id: 1
                    title: "Updated Blog Title"
                    content: "This is the updated content of the blog."
                    user: {
                      id: 1,
                      name: "Prebor Emmanuel"
                    }
        '404':
          description: Blog not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "Blog could not be located"
                    status: "not found"
                    code: 404
    delete:
      summary: Delete a blog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Blog deleted
        '404':
          description: Blog not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "Blog could not be located"
                    status: "not found"
                    code: 404

  /languages:
    post:
      summary: Create a new language
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Language'
            examples:
              example-1:
                value:
                  name: "English"
                  code: "en"
      responses:
        '201':
          description: Language has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Language'
              examples:
                example-1:
                  value:
                    id: 1
                    name: "English"
                    code: "en"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "Language could not be created"
                    status: "error"
                    code: 400
    get:
      summary: Get all languages
      responses:
        '200':
          description: Returns a list of languages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Language'
              examples:
                example-1:
                  value: [
                    {
                      "id": 1,
                      "name": "English",
                      "code": "en"
                    },
                    {
                      "id": 2,
                      "name": "French",
                      "code": "fr"
                    }
                  ]

  /regions:
    post:
      summary: Create a new region
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Region'
            examples:
              example-1:
                value:
                  name: "North America"
                  code: "NA"
      responses:
        '201':
          description: Region has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region'
              examples:
                example-1:
                  value:
                    id: 1
                    name: "North America"
                    code: "NA"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example-1:
                  value:
                    message: "Region could not be created"
                    status: "error"
                    code: 400
    get:
      summary: Get all regions
      responses:
        '200':
          description: Returns a list of regions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Region'
              examples:
                example-1:
                  value: [
                    {
                      "id": 1,
                      "name": "North America",
                      "code": "NA"
                    },
                    {
                      "id": 2,
                      "name": "Europe",
                      "code": "EU"
                    }
                  ]

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        status:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        code:
          type: integer
    MagicLinkRequest:
      type: object
      properties:
        email:
          type: string
    ChangePasswordRequest:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
    EmailRequest:
      type: object
      properties:
        emailTo:
          type: string
        subject:
          type: string
        body:
          type: string
    StripePaymentRequest:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
        source:
          type: string
    FlutterwavePaymentRequest:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
        source:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password_hash:
          type: string
        organization:
          $ref: '#/components/schemas/Organization'
    UserUpdateRequest:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
    Organization:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Blog:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        user:
          $ref: '#/components/schemas/User'
    Language:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          type: string
    Region:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          type: string
